spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081
          predicates:
          - Path=/membres/**
        - id: r2
          uri: http://localhost:8082
          predicates:

          - Path=/publications/**